Search component
WildCodeSchool-2024-02/JS-RMT-julien-TeamA-Project2 pull request #12
Opened 2024-05-31 11:59 UTC by MariaKSanz

2024-05-31 14:56 UTC, BastienDmr approved these changes, later dismissed

2024-05-31 14:57 UTC, NicolasFollain approved these changes, later dismissed

2024-05-31 15:28 UTC, jujuck requested changes

2024-05-31 15:28 UTC, jujuck commented on client/src/components/SearchBar.jsx
> +      <button type="button" onClick={handleLuckyClick}>
Passer sur un Link pour la navigation

2024-05-31 15:28 UTC, jujuck commented on client/src/App.jsx
> +        <p className="noMovieMessage">
Passer en mode direct avec un &&
filteredMovies.length === 0 && <p className="noMovieMessage">There is no movie matching your search, please try again.</p>}

2024-06-03 06:50 UTC, jujuck approved these changes

2024-06-03 06:50 UTC, merged