@feat/navigation
WildCodeSchool-2024-02/JS-RMT-julien-TeamA-Project2 pull request #14
Opened 2024-06-03 09:49 UTC by BastienDmr

2024-06-03 10:01 UTC, ITrogg submitted a review, later dismissed

2024-06-03 10:18 UTC, MariaKSanz submitted a review, later dismissed

2024-06-03 15:08 UTC, jujuck requested changes
+ revoir le css pour le bouton

2024-06-03 15:08 UTC, jujuck commented on client/src/components/Navigation.jsx
> +          <button type="button">Access favorites</button>
Pas de button, ecris juste texte

2024-06-04 08:15 UTC, NicolasFollain approved these changes

2024-06-04 08:15 UTC, ITrogg approved these changes

2024-06-04 08:19 UTC, jujuck approved these changes

2024-06-04 08:19 UTC, merged