@filter
WildCodeSchool-2024-02/JS-RMT-julien-TeamA-Project2 pull request #15
Opened 2024-06-03 14:24 UTC by NicolasFollain

2024-06-03 15:18 UTC, ITrogg approved these changes, later dismissed

2024-06-04 08:35 UTC, BastienDmr approved these changes, later dismissed

2024-06-04 08:37 UTC, ITrogg submitted a review, later dismissed

2024-06-04 10:07 UTC, jujuck requested changes

2024-06-04 10:07 UTC, jujuck commented on client/src/components/FilterBar.jsx
> +import PropTypes from "prop-types";
Ordre des imports

2024-06-04 10:17 UTC, BastienDmr approved these changes

2024-06-04 10:18 UTC, ITrogg approved these changes

2024-06-04 10:48 UTC, jujuck approved these changes

2024-06-04 10:48 UTC, merged