@feat/create context
WildCodeSchool-2024-02/JS-RMT-julien-TeamA-Project2 pull request #4
Opened 2024-05-28 09:41 UTC by ITrogg

2024-05-28 09:44 UTC, BastienDmr submitted a review, later dismissed

2024-05-28 09:44 UTC, MariaKSanz submitted a review, later dismissed

2024-05-28 13:40 UTC, jujuck requested changes

2024-05-28 13:40 UTC, jujuck commented on client/src/App.jsx
> +  console.info(fav, setFav);
On ne laisse pas de console.info ou de console.log dans le DEV

2024-05-28 13:40 UTC, jujuck commented on client/src/App.jsx
> +  console.info(fav, setFav);
Si ceci fait parti du test de fonctionnement, tout supprimer. Le context est mis en place et sera consommé ultérieurement

2024-05-29 08:47 UTC, MariaKSanz approved these changes

2024-05-29 08:49 UTC, BastienDmr approved these changes

2024-05-29 09:26 UTC, jujuck approved these changes

2024-05-29 09:26 UTC, merged